name: Go

on: 
  push:
    tags:
      - 'v*.*.*' # Trigger auf Versionstags wie v1.0.0

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: ./getdeps.cmd

    - name: Build
      run: ./build.cmd

    - name: Run tests
      run: ./test.cmd

    - name: Upload binary to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./go-calendarweektray.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
