name: Go 

on:
  push:
    tags:
      - 'v*.*.*' # Dies sorgt dafür, dass der Workflow bei Versionstags wie v1.0.0 ausgelöst wird
  workflow_dispatch: # Ermöglicht manuelles Auslösen

jobs:
  build:
    name: Build
    runs-on: windows-latest

    permissions:
      contents: write
      issues: write
      pull-requests: write
      deployments: write
      actions: write
      
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get the current commit SHA
      id: vars
      run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Get the current time
      id: time
      run: echo "time=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

    - name: Get dependencies
      run: ./getdeps.cmd

    - name: Build
      run: go build -ldflags "-X main.semVer=${{ github.ref_name }} -X main.sha1ver=${{ env.sha }} -X main.buildTime='${{ env.time }}'" -o Kalenderwoche.exe

    - name: Run tests
      run: ./test.cmd

    - name: Upload binary to pre-release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./Kalenderwoche.exe
        prerelease: true
