name: Go

on:
  push:
    tags:
      - 'v*.*.*' # Workflow wird bei Versionstags wie v1.0.0 ausgelöst
  workflow_dispatch: # Ermöglicht manuelles Auslösen

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: ./getdeps.cmd

    - name: Build
      run: go build -ldflags "-X main.semVer=${{ github.ref_name }} -X main.sha1ver=$(git rev-parse --short HEAD) -X main.buildTime=$(date -u +'%Y-%m-%d %H:%M:%S')" -o Kalenderwoche.exe

    - name: Run tests
      run: ./test.cmd

    - name: Upload binary to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ./Kalenderwoche.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
